version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: task-tracker
    main: ./cmd/main.go

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: lr1ne
    name: Task-Tracker

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"